### ISSUE TITLE
pr2_dashboard dependencies are missing  (ros ticket #2346)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#11]
I run rosmake pr2_dashboard.

Then I run rosrun pr2_dashboard pr2_dashboard and get the following:

ultimately pr2_dashboard will run if I build enough random things, but it would be nice to fix the dependencies.

{{{
cmeyers@ots:~/projects/ros$ rosrun pr2_dashboard pr2_dashboard 
Traceback (most recent call last):
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/pr2/pr2_dashboard/scripts/pr2_dashboard", line 50, in <module>
    import pr2_dashboard
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/pr2/pr2_dashboard/src/pr2_dashboard/**init**.py", line 1, in <module>
    from pr2_frame import *
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/pr2/pr2_dashboard/src/pr2_dashboard/pr2_frame.py", line 48, in <module>
    import hardware_panel
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/pr2/pr2_dashboard/src/pr2_dashboard/hardware_panel.py", line 41, in <module>
    from ocean_battery_driver.ibps_panel import *
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/pr2_drivers/ocean_battery_driver/src/ocean_battery_driver/ibps_panel.py", line 43, in <module>
    from robot_msgs.msg import *
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/common_msgs/robot_msgs/src/robot_msgs/msg/**init**.py", line 2, in <module>
    from _VOPose import *
  File "/u/cmeyers/projects/ros/ros-pkg/stacks/common_msgs/robot_msgs/src/robot_msgs/msg/_VOPose.py", line 5, in <module>
    import geometry_msgs.msg
ImportError: No module named geometry_msgs.msg

}}}

trac data:
- Owner: **jfaust**
- Reporter: **cmeyers**
- Reported at: **Mon Aug 10 13:19:55 2009**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/2346

**Comment by ahendrix** [comment]
[jfaust] It looks like you have some old state in your system -- robot_msgs exists in that callstack, but does not exist anymore.  Does this still happen w/latest code?

**Comment by ahendrix** [comment]
[cmeyers] This was the latest code as of when I opened the ticket. Maybe it is confused about something old and left over?

I originally saw this problem with a new tree but that was a few weeks ago.

**Comment by ahendrix** [comment]
[jfaust] Just checked out a fresh ros-pkg tree, did a rosmake, and it worked -- going to assume this was fixed, or part of strange machine state.

**Comment by ahendrix** [comment]
[cmeyers] OK, people said file it so I did. Thanks.
