### ISSUE TITLE
robot stop prints exception if it can't connect to c2  (ros ticket #3889)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#126]
Saw the following exception when running {{{robot stop}}} on PRI immediately after turning the robot on:

{{{
tfield@pri1:~$ sudo robot stop
Traceback (most recent call last):
  File "/usr/bin/ckill", line 386, in <module>
    main(sys.argv, sys.stdout, os.environ)
  File "/usr/bin/ckill", line 376, in main
    ri.list()
  File "/usr/bin/ckill", line 257, in list
    todo = self.kill_list(host)
  File "/usr/bin/ckill", line 187, in kill_list
    pl = ProcessList([host])
  File "/usr/bin/ckill", line 91, in **init**
    self.fetch()
  File "/usr/bin/ckill", line 97, in fetch
    self.fetch_process_list(host)
  File "/usr/bin/ckill", line 106, in fetch_process_list
    stdout = spawn(cmd)
  File "/usr/bin/ckill", line 60, in spawn
    raise ProcessError, "Error: %s" % stderr
**main**.ProcessError: Error: ssh: connect to host c2 port 22: No route to host

kyamazaki currently has control of the robot.
Do you wish to replace them? [(y)es/(n)o]:y
Stealing control of the robot from kyamazaki.
No processes to kill.
Releasing control of the robot.
tfield@pri1:~$ 
}}}

Worked (with no exception) the next execution straight after.

trac data:
- Owner: **leibs**
- Reporter: **tfield**
- Reported at: **Wed Feb 17 17:39:17 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/3889

**Comment by ahendrix** [comment]
[leibs] Yeah, looks like ckill has problems if machine 2 isn't up.

**Comment by ahendrix** [comment]
[leibs] https://code.ros.org/trac/pr2debs/ticket/16
