### ISSUE TITLE
Error from pr2_camera_synchronizer  (ros ticket #4218)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#154]
I'm seeing the following error on latest for the pr2_camera_synchronizer.

{{{
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/u/eitan/ros_latest/stacks/pr2_robot/pr2_camera_synchronizer/src/pr2_camera_synchronizer/synchronizer_classes.py", line 105, in run
    self.f(_allargs[0], *_allargs[1])
  File "/u/eitan/ros_latest/stacks/pr2_robot/pr2_camera_synchronizer/src/pr2_camera_synchronizer/synchronizer_classes.py", line 450, in async_apply_update
    self.reconfigure_client.update_configuration(reconfig_request)
  File "/u/eitan/ros_latest/stacks/driver_common/dynamic_reconfigure/src/dynamic_reconfigure/client.py", line 158, in update_configuration
    raise DynamicReconfigureParameterException('don\'t know parameter: %s' % name)
DynamicReconfigureParameterException: don't know parameter: max_exposure

}}}

trac data:
- Owner: **wim**
- Reporter: **eitan**
- Reported at: **Mon Apr 19 17:18:26 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4218

**Comment by ahendrix** [comment]
[eitan] My bad... didn't do a rosmake for pr2_bringup after an update.
