### ISSUE TITLE
calibrate_pr2.py died after long wait for motors halted  (ros ticket #4307)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#167]
Error message:
{{{
Traceback (most recent call last):
  File "/u/wgtest/ros/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 423, in <module>
    if **name** == '**main**': main()
  File "/u/wgtest/ros/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 278, in main
    if last_joint_states:
NameError: global name 'last_joint_states' is not defined
}}}

Suggested patch:
{{{
# Index: calibrate_pr2.py

--- calibrate_pr2.py    (revision 36516)
+++ calibrate_pr2.py    (working copy)
@@ -70,6 +70,7 @@
 publishers = []
 calibration_params_namespace = "calibration_controllers"

+last_joint_states = None

 def joint_states_cb(msg):
     global last_joint_states
}}}

trac data:
- Owner: **wim**
- Reporter: **watts**
- Reported at: **Tue May 11 09:37:19 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4307

**Comment by ahendrix** [comment]
[wim] Is this Boxturtle or latest?

**Comment by ahendrix** [comment]
[wim] Fixed in trunk
