### ISSUE TITLE
calibrate_pr2.py crashes when arm is not found  (ros ticket #4548)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#188]
{{{
Traceback (most recent call last):
  File "/u/gunter/ros/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 434, in <module>
    if **name** == '**main**': main()
  File "/u/gunter/ros/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 364, in main
    calibrate_group(b_arm_group)
  File "/u/gunter/ros/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 216, in calibrate_group
    calibrate(joints)
  File "/u/gunter/ros/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 108, in calibrate
    if services[j]().is_calibrated:
KeyError: 'l_shoulder_pan'
[calibrate_pr2-2] process has died [pid 22046, exit code 1].
}}}

This is on PRG, which is lacking a left arm.  The calibrate script should be robust to missing joints and continue to calibrate all the joints that are present.

trac data:
- Owner: **wim**
- Reporter: **gunter**
- Reported at: **Mon Jul 12 21:04:28 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4548

**Comment by ahendrix** [comment]
[wim] I think you are running an old version of the pr2_robot stack. When you run version >= 1.0.0 this should be fixed.
