### ISSUE TITLE
Belt Transmission Problems PRL  (ros ticket #4912)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#202]
I switched away from using the belt transmissions on PRL because I couldn't actually get things to come up. This was after I went through the pain of trying to figure out what I needed to add to my ROS_PACKAGE_PATH to get things up and running which involved looking into your home directory on the robot. If you want people to use the new transmissions, I think you need to put some more work into making sure its a relatively easy experience. Right now, it really sucks.

A sample of some of the errors I was getting.

{{{
Exception rospy.service.ServiceException: ServiceException('unable to connect to service: [Errno 111] Connection refused',) in <bound method CalibrateParallel.__del__ of <__main__.CalibrateParallel instance at 0x2fee998>> ignored
Traceback (most recent call last):
  File "/pr/1/eitan/belt/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 418, in <module>
    if **name** == '**main**': main()
  File "/pr/1/eitan/belt/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 397, in main
    del arm
UnboundLocalError: local variable 'arm' referenced before assignment

}}}

{{{
[realtime_loop-1] process has died [pid 28899, exit code -11].
log files: /u/eitan/.ros/log/a612c1ce-f733-11df-8e64-001517c0137d/realtime_loop-1_.log
[calibrate_pr2-2] process has died [pid 28902, exit code 1].
log files: /u/eitan/.ros/log/a612c1ce-f733-11df-8e64-001517c0137d/calibrate_pr2-2_.log
}}}

trac data:
- Owner: **sglaser**
- Reporter: **eitan**
- Reported at: **Tue Nov 23 11:09:05 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4912

**Comment by ahendrix** [comment]
[sglaser] The belt transmissions just work when you use the standard cturtle install.  It looks like you may have done unnecessary (and unhelpful) extra work to configure your account.  In particular, the current setup on PRL doesn't reference anything in my home directory.

Here's what the setup should look like.  Make sure your configuration matches up:
{{{
 sglaser@prl1:~$ rospack find pr2_mechanism_model
/opt/ros/cturtle/unstable/pr2_mechanism/pr2_mechanism_model
 sglaser@prl1:~$ rospack find pr2_robot
/opt/ros/cturtle/unstable/pr2_mechanism/pr2_robot
}}}

My guess is that you followed the directions here: http://www.ros.org/wiki/StuartGlaser/RunningBeltCompensation .  Don't do that.  PRL has been set up specially so that you only need to `source /opt/ros/cturtle/setup.bash`.

**Comment by ahendrix** [comment]
[eitan] Ok... my bad, somehow I missed the /opt/ros/cturtle/unstable bit. On another note, I'm putting lucid onto PRL right now, so that may screw with things a bit... we may need to set it up again.

**Comment by ahendrix** [comment]
[sglaser] Cool.  Ping me when lucid's done and I'll fix the setup.
