### ISSUE TITLE
pr2_computer_monitor tests fail in unstable devel branch of pr2_robot  (ros ticket #4990)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#211]
Here is an example Hudson test http://build.willowgarage.com/job/prerelease_unstable_pr2_common_pr2_robot_maverick_i386/2/consoleText. This is currently blocking the release of pr2_robot for diamondback.

{{{
[ROSUNIT] Outputting test results to /u/wim/.ros/test_results/pr2_computer_monitor/TEST-rostest__test_parse_test.py.xml
Traceback (most recent call last):
  File "/wg/nhx/wim/ros_unstable/pr2_robot/pr2_computer_monitor/test/parse_test.py", line 44, in <module>
    import pr2_computer_monitor
  File "/u/wim/ros_unstable/pr2_robot/pr2_computer_monitor/src/pr2_computer_monitor/**init**.py", line 1, in <module>
    from nvidia_smi_util import gpu_status_to_diag, parse_smi_output, get_gpu_status
  File "/u/wim/ros_unstable/pr2_robot/pr2_computer_monitor/src/pr2_computer_monitor/nvidia_smi_util.py", line 40, in <module>
    import roslib; roslib.load_manifest(PKG)
  File "/u/wim/ros_unstable/ros/core/roslib/src/roslib/launcher.py", line 69, in load_manifest
    sys.path = _generate_python_path(package_name, [], os.environ) + sys.path
  File "/u/wim/ros_unstable/ros/core/roslib/src/roslib/launcher.py", line 105, in _generate_python_path
    manifest_file = roslib.manifest.manifest_file(pkg, True, env)
  File "/u/wim/ros_unstable/ros/core/roslib/src/roslib/manifest.py", line 117, in manifest_file
    d = roslib.packages.get_pkg_dir(package, required, ros_root=env[roslib.rosenv.ROS_ROOT]) 
  File "/u/wim/ros_unstable/ros/core/roslib/src/roslib/packages.py", line 213, in get_pkg_dir
    raise InvalidROSPkgException("Cannot locate installation of package %s: %s. ROS_ROOT[%s] ROS_PACKAGE_PATH[%s]"%(package, rperr.strip(), ros_root, ros_package_path))
roslib.packages.InvalidROSPkgException: Cannot locate installation of package nvidia_gpu_monitor: [rospack] couldn't find package [nvidia_gpu_monitor]. 
}}}

trac data:
- Owner: **watts**
- Reporter: **wim**
- Reported at: **Fri Jan 21 12:25:34 2011**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4990

**Comment by ahendrix** [comment]
[watts] r48207

Thanks for catching that.
