### ISSUE TITLE
ddwrt node dies during robot launch  (ros ticket #5078)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#215]
The ddwrt node in `/etc/ros/robot.launch` intermittently dies with this exception:

{{{
Traceback (most recent call last):
  File "/opt/ros/diamondback/stacks/wifi_drivers/wifi_ddwrt/nodes/ddwrt.py", line 267, in <module>
    main(sys.argv, sys.stdout, os.environ)
  File "/opt/ros/diamondback/stacks/wifi_drivers/wifi_ddwrt/nodes/ddwrt.py", line 264, in main
    loop()
  File "/opt/ros/diamondback/stacks/wifi_drivers/wifi_ddwrt/nodes/ddwrt.py", line 223, in loop
    if e != last_e:
NameError: global name 'last_e' is not defined
}}}

Looks like `ddwrt.py:223` should have `last_ex` not `last_e`.

trac data:
- Owner: **gerkey**
- Reporter: **tfield**
- Reported at: **Wed Mar 16 16:44:54 2011**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/5078

**Comment by ahendrix** [comment]
[wim] I think most stack maintainers would not mind if you just check in trivial fixes like this.  But I don't want to complain, I really appreciate that you even file tickets about the problems you see. Anyway, I checked your patch into trunk:

$ svn ci -m "fix typo, ticket #5078"
Sending        wifi_ddwrt/nodes/ddwrt.py
Transmitting file data .
Committed revision r50153.

As far as I can tell from the stack.xml, James is maintaining this stack. James, could you push out a new release when you have time?

**Comment by ahendrix** [comment]
[tfield] I should have been clearer in my ticket.  There's the obvious typo with the corresponding trivial fix, but an exception is being thrown to cause that typo to be executed.

Presumably, the exception is new, otherwise this would have manifested itself previously.

**Comment by ahendrix** [comment]
[wim] So James denies all knowledge about this stack ;-) Any idea who's the current maintainer?

**Comment by ahendrix** [comment]
[blaise] I think Scott H. may have written it, and as far as I know it has been bouncing around like a hot potato ever since.

In my opinion the messages it uses are horrid as they use strings for things that should be numeric (ticketed elsewhere), and never got a proper review.

**Comment by ahendrix** [comment]
[gerkey] A quick look at the code suggests that it was written with the expectation that exceptions would be thrown from the underlying wifi stuff, and that they can all be safely ignored.  

I would guess that exceptions have been thrown occasionally since the beginning, and that the typo has caused the node to die when that happened, also since the beginning.  It's just that nobody noticed or cared.

I kicked off prerelease builds for wifi_drivers in unstable and diamondaback.  When they come back, I'll release 0.1.5.

**Comment by ahendrix** [comment]
[gerkey] wifi_drivers 0.1.5 released into diamondback and unstable.  Speak up if you also want a cturtle release.
