### ISSUE TITLE
pre defs are broken  (ros ticket #3468)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#59]
{{{
 sglaser@pre1:~/ros/dev/wg-ros-pkg/stacks/pr2_common_alpha/pr2_defs/robots$ rosrun xacro xacro.py pre.urdf.xacro 
Traceback (most recent call last):
  File "/u/sglaser/ros/dev/common/xacro/xacro.py", line 35, in <module>
    xacro.main()
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 510, in main
    eval_self_contained(doc)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 451, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 416, in eval_all
    eval_all(body, macros, scoped)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 435, in eval_all
    result = eval_text(at[1], symbols)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 366, in eval_text
    results.append(handle_expr(lex.next()[1][2:-1]))
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 354, in handle_expr
    return eval_expr(lex, symbols)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 335, in eval_expr
    n = eval_term(lex, symbols)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 303, in eval_term
    result = eval_factor(lex, symbols)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 284, in eval_factor
    return neg \* eval_lit(lex, symbols)
  File "/u/sglaser/ros/dev/common/xacro/src/xacro.py", line 262, in eval_lit
    raise XacroException("Property wasn't defined: %s" % str(ex))
xacro.XacroException: Property wasn't defined: u'base_collision_size_z'
}}}

trac data:
- Owner: **wim**
- Reporter: **sglaser**
- Reported at: **Fri Jan  8 17:05:19 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/3468

**Comment by ahendrix** [comment]
[hsu] xacro parses again! sorry about that.

r28773

**Comment by ahendrix** [comment]
[hsu] Wim,
I'll let you close since you have to regenerate /etc/pr2/urdf/*
Thanks,
John

**Comment by ahendrix** [comment]
[wim] We never changed the urdf on pre. I'll do that when we move pre to the new pringup launch file.
