### ISSUE TITLE
pr2_dashboard_aggregator doens't work  (ros ticket #3544)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_robot#77]
Package rename failed.

{{{
Traceback (most recent call last):
  File "/u/wgtest/ros_nav_test/pkgs/wg-ros-pkg-trunk/stacks/pr2_robot/pr2_dashboard_aggregator/dashboard_aggregator.py", line 35, in <module>
    import roslib; roslib.load_manifest('dashboard_aggregator')
  File "/u/wgtest/ros_nav_test/ros/core/roslib/src/roslib/launcher.py", line 69, in load_manifest
    sys.path = _generate_python_path(package_name, [], os.environ) + sys.path
  File "/u/wgtest/ros_nav_test/ros/core/roslib/src/roslib/launcher.py", line 105, in _generate_python_path
    manifest_file = roslib.manifest.manifest_file(pkg, True, env)
  File "/u/wgtest/ros_nav_test/ros/core/roslib/src/roslib/manifest.py", line 117, in manifest_file
    d = roslib.packages.get_pkg_dir(package, required, ros_root=env[roslib.rosenv.ROS_ROOT]) 
  File "/u/wgtest/ros_nav_test/ros/core/roslib/src/roslib/packages.py", line 204, in get_pkg_dir
    raise InvalidROSPkgException("Cannot locate installation of package %s: %s. ROS_ROOT[%s] ROS_PACKAGE_PATH[%s]"%(package, rperr.strip(), ros_root, ros_package_path))
roslib.packages.InvalidROSPkgException: Cannot locate installation of package dashboard_aggregator: [rospack] couldn't find package [dashboard_aggregator]. ROS_ROOT[/u/wgtest/ros_nav_test/ros] ROS_PACKAGE_PATH[/u/wgtest/ros_nav_test/pkgs]
[c2-0]: launching nodes...
[pr2_dashboard_aggregator-27] process has died [pid 2819, exit code 1].
}}}

trac data:
- Owner: **wim**
- Reporter: **watts**
- Reported at: **Wed Jan 13 13:56:19 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/3544

**Comment by ahendrix** [comment]
[watts] r29051.
